apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager-backend
  template:
    metadata:
      labels:
        app: taskmanager-backend
      annotations:
        deployment.kubernetes.io/revision: "3"
    spec:
      containers:
        - name: backend
          image: taskmanager-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: jwt-secret
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-config
                  key: spring-datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: db-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-config
                  key: spring-ddl-auto
            - name: APP_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: jwt-secret