apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret
type: Opaque
data:
  db-username: dGFza3VzZXI=
  db-password: dGFza3Bhc3N3b3Jk
  jwt-secret: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1N3U4N3gyL0ExM0Y0NDI4NDcyQjRCNjI1MDZkNTM2NzU2Nms1OTcw
