spring.application.name=taskmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/devops_saas
spring.datasource.username=devuser
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
